export const GET_ALL_FUNDS_ON_SEARCH = 'GET_ALL_FUNDS_ON_SEARCH';
export const GET_ALL_FUNDS_FAILED_ON_SAERCH = 'GET_ALL_FUNDS_FAILED_ON_SAERCH';
export const GET_ALL_FUNDS_PENDING_ON_SAERCH = 'GET_ALL_FUNDS_PENDING_ON_SAERCH';
