export const GET_ALL_FUNDS_ON_SEARCH = 'GET_ALL_FUNDS_ON_SEARCH';
export const GET_ALL_FUNDS_FAILED_ON_SEARCH = 'GET_ALL_FUNDS_FAILED_ON_SEARCH';
export const GET_ALL_FUNDS_PENDING_ON_SEARCH = 'GET_ALL_FUNDS_PENDING_ON_SEARCH';
